### ISSUE TITLE
[12.0] stock_inventory_valuation_report - Attribute error

### ISSUE THREAD

**Issue by microsound1** [OCA/stock-logistics-reporting#81] opened 2019-11-18 18:56 UTC
When I do an inventory valuation and click on "Export PDF" or "Export XLS" it gives : AttributeError: 'product.product' object has no attribute 'cost_currency_id' 
Anyone experienced with this or is there a solution?

If you need a full error, please let me know i can provide it, thank you.

**Comment by bodedra** [comment] 2019-11-25 08:00
@microsound1 : I have tried at runbot http://3397314-12-0-a7e91a.runbot2-2.odoo-community.org/web?debug=1#action=331&active_id=6&menu_id=82 but unable to reproduce it.

It seems you have old revision of Odoo core modules.

Here is reference of `cost_currency_id` field declaration in Odoo `product` core module https://github.com/odoo/odoo/blob/12.0/addons/product/models/product_template.py#L60

**Comment by rousseldenis** [comment] 2019-11-25 21:13
@microsound1 Can you check your version as @bodedra said ?

**Comment by bodedra** [comment] 2019-11-30 06:57
@rousseldenis We may close this as no answer from @microsound1

**Comment by rousseldenis** [comment] 2019-11-30 09:06
> @rousseldenis We may close this as no answer from @microsound1

@bodedra Let a little bit more time. People can be on holidays or... :smiley:

**Comment by microsound1** [comment] 2019-12-14 09:13
Sorry for the delay and thank you for the hint @bodedra 
I updgraded product in the addon folder to the latest version and it works perfectly.

**Closed as completed** 2019-12-14 12:37 UTC
